### PR TITLE
build upstream changes

### PR DESCRIPTION
**Pull request by walez**

### CODE REVIEW

**Review by yomexzo — APPROVED** [review]

**Comment by yomexzo** [comment]
@walez, how did you generate the file.

may be add a `CONTRIBUTING` file to the repo with guide/instructions on how to contribute?

**Comment by yomexzo** [comment]
@walez, it's deployed but the link at the bottom are still not linked. See https://forloop.africa

**Comment by walez** [comment]
@yomexzo will add a CONTRIBUTING.md maybe tomorrow with a guide.

**Comment by walez** [comment]
The footer items have actually been linked since, it's how the css is that is causing the issue.
if you inspect the element you will see that the footer section has been given a fixed position and every other content on the page overlays it

**Pull request merged**
