### PR TITLE
Add GitHub link to footer and update copyright year

### PR DESCRIPTION
**Pull request by acekyd**

### CODE REVIEW

**Comment by yomexzo** [comment]
thanks a lot @acekyd. Minding linking the github icon on the top-right as well? See image below.

screenshot 2017-09-17 19 57 24

this fixes #7

**Comment by yomexzo** [comment]
nvm @acekyd, it is already. Thanks again!

**Review by yomexzo — APPROVED** [review]

**Comment by acekyd** [comment]
@yomexzo #7 says github repo but those links are just to the forLoopOfficial account.

**Comment by yomexzo** [comment]
@acekyd, it seems some sort of build is required. Deployed and it is not still linked. I also made [this commit](https://github.com/forLoopOfficial/forLoop-website/commit/ec8da3f8db101327bd5a8a83a34bd438c44c6aae) thinking another file needed to be edited.

I tried using the `gulp` script but getting `vue` errors related to dependency versions mismatch. We may have to also pin dependency versions in `package.json` and `composer.json`

**Comment by yomexzo** [comment]
are you able to view the changes locally?

**Comment by acekyd** [comment]
Try inspecting element @yomexzo... it's most likely not clickable cos of #4. I didn't try setting up locally, would do now.

**Comment by yomexzo** [comment]
@acekyd, i think they are not clickable because `href=""`. Default browser behaviour when `href` is missing or empty.

I noticed a bigger problem @walez has changes (from Sept 13, 2017) on Heroku that is not here in mainstream (`master` branch here). It is preventing the deploy from being successful. The changes @acekyd made might be the correct changes.

I do not want to do a `git push --force`. @walez, kindly get your changes on to master here so we don't loose your changes while shipping.

You do not need to worry about deploying manually anymore. I have set up automatic deploy such that Heroku is updated when `master` branch is updated (e.g a merge is done)

**Comment by yomexzo** [comment]
re: `master` not being updated. I was able to merge `heroku/master` into upstream here.

I have deployed and still nothing.

@walez, kindly advice.

**Comment by yomexzo** [comment]
@acekyd, you are right. Even Twitter is not clickable. But the added `href` for github is not in the DOM.

**Comment by walez** [comment]
@acekyd @yomexzo tried fixing the footer link not being clickable before and it seemed like an element with a higher z-index was overlaying the footer, preventing the links from being clickable any suggestions to fix is appreciated

**Comment by walez** [comment]
@yomexzo you will need to run `npm run prod` before pushing your commit for the vue file changes to reflect, wanted to put it as part of the heroku deployment flow but our build pack is based on PHP and not Nodejs

**Comment by acekyd** [comment]
I see the changes are showing up now, any particular update to take note of? @yomexzo @walez

**Pull request merged**
